### PR TITLE
routines diagram

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
As the title says.

### CODE REVIEW

**Review by andrea-pasquale — COMMENTED** [review]
Thanks @Edoardo-Pedicillo.
Could you please upload also the SVG?

**Comment by andrea-pasquale** [comment]
Also I would change `CZ` into `Tune landscape` and we should remove the `filtered RB`

**Comment by MatteoRobbiati** [comment]
Many thanks @Edoardo-Pedicillo. 
I would suggest to fix the diagram contents according with @andrea-pasquale suggestions and then, once I standardize it with the other diagrams, we can upload all the types (PNG, SVG, PDF, Xmind).

**Comment by Edoardo-Pedicillo** [comment]
> Many thanks @Edoardo-Pedicillo.
I would suggest to fix the diagram contents according with @andrea-pasquale suggestions and then, once I standardize it with the other diagrams, we can upload all the types (PNG, SVG, PDF, Xmind).

Ok, I have uploaded the diagram with Andrea's suggestion.

**Comment by andrea-pasquale** [comment]
Thanks @Edoardo-Pedicillo and @MatteoRobbiati.
I made a few corrections to some entries in the diagram.
I'll merge it now.

**Pull request merged**
