### PR TITLE
Add clifford and Qibotn simulators to main diagram

### PR DESCRIPTION
**Pull request by MatteoRobbiati**

### CODE REVIEW

**Comment by scarrazza** [comment]
Could you please add the quantum info module?

**Comment by MatteoRobbiati** [comment]
> Maybe we should remove the bold from qibojit or add it to all our backends.

Originally I was using the bold to refer to individual packages (Qibo, Qibolab, Qibojit, Qibocal, etc.). We can remove it if it is not clear.

**Comment by scarrazza** [comment]
I see that Qibotn is not in bold.

**Comment by MatteoRobbiati** [comment]
> I see that Qibotn is not in bold.

Yes, that was a mistake. Would you prefer to make it bold or to remove bold from the others?

**Pull request merged**
