### PR TITLE
Update simulation backends in docs

### PR DESCRIPTION
**Pull request by alecandido**

### CODE REVIEW

**Comment by scarrazza** [comment]
Thanks @alecandido but could you please improve the separation between lightweight/specialized/GPU?

**Comment by scarrazza** [comment]
Yes, that is better.

**Review by MatteoRobbiati — COMMENTED** [review]
Thanks @alecandido!

I would keep the grouping boxes (because they help in separating the blocks) but I would use opacity = 0 so that you have them without seeing the black contours (which is also problematic with the night version of the docs).

And please make the boxes a bit wider because, at least with my browser, they are not rendered properly:

texts

**Comment by alecandido** [comment]
> And please make the boxes a bit wider because, at least with my browser, the SVG is not rendered properly:

I believe this is a workaround to the proper solution: we should either embed the font in the SVG, or add the font to the webpage.
If you produce the picture with one font, and then look at it with another, it will always be slightly messed up.

**Comment by alecandido** [comment]
Moreover, it's hard to make a single picture that works well on dark and light backgrounds, so the solutions are:
1. make two versions of the diagrams
2. double borders, e.g. an internal dark border and an external white one (the white will be invisible on a white background, but it will make the internal visible on a dark bacground)
3. use a uniform background color for diagrams in the light and dark theme

Option 1. is terrible, because we're making them manually, and you already have to export by hand in multiple formats every time. The second is feasible, but still a bit annoying (and possibly not supported by XMind).
I'd suggest the uniform background (or closer, doesn't have to be the exact same). You could decide for a greyish one, or with a given color.
But we're always drawing diagrams on a white background, so I'd just keep the white background even for the dark theme (for the light it will be just uniform, and for the dark will become an inset).

**Pull request merged**
