### PR TITLE
Add qibochem to qibo diagram

### PR DESCRIPTION
**Pull request by MatteoRobbiati**

### CODE REVIEW

**Review by scarrazza — COMMENTED** [review]
Please remove the white background.

**Review by scarrazza — COMMENTED** [review]
Thanks. The resolution of the png image is smaller than the original, is that okay?

**Comment by MatteoRobbiati** [comment]
> Thanks. The resolution of the png image is smaller than the original, is that okay?

I think it is due to the fact Xmind automatically set the resolution depending on the diagram proportion. I think it is enough for the docs.

**Comment by MatteoRobbiati** [comment]
> > Thanks. The resolution of the png image is smaller than the original, is that okay?
> 
> I think it is due to the fact Xmind automatically set the resolution depending on the diagram proportions. I think it is enough for the docs.

**Comment by scarrazza** [comment]
Perfect.

**Pull request merged**
