### PR TITLE
Updating qibocal plot

### PR DESCRIPTION
**Pull request by andrea-pasquale**
I'm going to put this new plot in the documentation after the refactor introduced by https://github.com/qiboteam/qibocal/pull/406

Let me know if you like it

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Thanks @MatteoRobbiati.

> 1. set the background colors in the boxes to have opacity equal to 100%, otherwise the scheme will become weird if shown in dark mode on the documentation. I am speaking about the comments boxes;

You mean the boxes where there is the description of each command?




> 2\. use lighter colors for the inner part of the boxes and a stronger one for the border, like is done in the other diagrams (now I am speaking about the `qq` boxes).

Ok, now I was using the same color for each line and I was just playing with the opacity. I will change it.

**Comment by MatteoRobbiati** [comment]
> You mean the boxes where there is the description of each command?

Yes.

> Ok, now I was using the same color for each line and I was just playing with the opacity. I will change it.

I also did this, but then if you switch the docs mode to dark it becomes weird. I would suggest you to keep one light color  with opacity 100% as default (you can play with the color palette in Xmind) and then select a stronger color for the borders.

**Comment by andrea-pasquale** [comment]
I modified the plot by adding your suggestions. Maybe I could have chosen better colors... Feel free to change them if you don't like it.

**Comment by MatteoRobbiati** [comment]
Many thanks @andrea-pasquale! It was nearly perfect. I just used a bit lighter version of your chosen colors for boxes and borders. Let me know if it is ok with you. Then I think we can merge.

**Comment by andrea-pasquale** [comment]
Thanks @MatteoRobbiati

**Pull request merged**
